# gems: feed
details:
    name: Lorem Restaurant
    address:
        - Stationstraat 5
        - 8000 Brugge
        - Belgium
    phone:
        - "0032497433263"
        - "0032479567234"
        - "003250342881"
    slogan: This restaurant is the most fabulous restaurant of Bruges and surrounding areas. The owners are very humble.
design:
    colours: #don't forget the "#" in the implementation
        accent: "745820"
        light: "030201"
        dark: "fafbfa"
sass:
    style: compressed
