# gems: feed
details:
    name: Lorem Restaurant
    address:
        - Stationstraat 5
        - 8000 Brugge
        - Belgium
    maps:
        query: "Lorem+Restaurant+Stationstraat+5+8000+Bruges+Belgium"
        token: AIzaSyBRi-XI8GF4aou1HrxLRpevEcaW9Wy9Pc0
    phone:
        - "+32 50 342 881"
        - "+32 497 433 263"
        - "+32 479 567 234"
    slogan: This restaurant is the most fabulous restaurant of Bruges and surrounding areas. The owners are very humble. #shorter description
    description: >
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores ipsa voluptatem ducimus mollitia id ratione, repellat quia nemo, nulla, voluptatum earum officiis. Quo ea porro et. Quaerat deleniti voluptates officiis.
    email: info@loremrestaurant.com
    twitter: loremrestaurant
    facebook: lorembrugge
design:
    colours: #don't forget the "#" in _includes/header.html
        accent: "740304" #also change in _sass/_variables.scss
sass:
    style: compressed
# disqus: haroenvtrip
# google-analytics: "UA-27277115-3"
